# 🚀 NumPy: The Powerhouse of Numerical Computing in Python

NumPy provides Python with an **extensive math library** capable of performing numerical computations effectively and efficiently.

---

## 🆚 Python Lists vs NumPy Arrays

While Python lists are incredibly flexible, **NumPy offers significant advantages**, especially when working with large datasets:

### ⚡ Speed
- NumPy can be **orders of magnitude faster** than native Python lists.
- This speed comes from:
  - **Memory-efficient** layout of NumPy arrays.
  - **Optimized C-based algorithms** used under the hood for arithmetic, statistics, and linear algebra.

---

## 🔢 Multidimensional Arrays: Vectors & Matrices

One of the biggest flexes of NumPy is its **support for multidimensional arrays**:

- NumPy arrays (also called `ndarray`) can represent:
  - **Vectors** (1D arrays)
  - **Matrices** (2D arrays)
  - **Tensors** (3D+ arrays)

---

## 🧠 Core Concept: The `ndarray`

At the core of NumPy lies the:

```python
ndarray  # nd stands for "n-dimensional"


In [ ]:
import numpy as np

### Create ndarray :---

In [16]:
# Creating an 1D ndarray that contains only integers
a = np.array([10,20,30,40,50])
print('a =',a) # a = [10,20,30,40,50]
print('a has dimensions: ',a.shape) # a has dimention: (5,)
print('The elemnt in a are of type: ', a.dtype) # The element in a are of type: int64

# Creating a 2D ndarray that conatins only integers
b = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('b has dimentions: ', b.shape) # b has dimentions:  (4, 3)
print('b has a total of', b.size, ' elements') # b has a total of 12  elements
print('b has an object of type: ', type(b)) # b has an object of type:  <class 'numpy.ndarray'>
print('The elements of b are of type: ', b.dtype) # The elements of b are of type:  int64

a = [10 20 30 40 50]
a has dimensions:  (5,)
The elemnt in a are of type:  int64
b has dimentions:  (4, 3)
b has a total of 12  elements
b has an object of type:  <class 'numpy.ndarray'>
The elements of b are of type:  int64


### Create ndarray with dtype :---

In [22]:
# Specifying the dtype when creating the ndarray
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(x)

[1 2 3 4 5]


### Save and load :---

In [25]:
# saving an array into a file
np.save('saved_array', x)

# Now loading the saved array from current Directory
y = np.load('./saved_array.npy')
print(y)

[1 2 3 4 5]


### Zeros, Ones, Full :---

In [29]:
# Creating ndarray using built-in functions
# 2 x 3 ndarray full of zeros
# synts :- np.zeros(shape)
zeroArr = np.zeros((2,3))
print(zeroArr)

# a 3 x 2 matrix full of ones
# syntax :- np.ones((3,2))
oneArr = np.ones((3,2))
print(oneArr)

# 2 x 3 ndarray full of 9's
# syntax :- np.full(shape, constant_value)
constArr = np.full((2,3), 9)
print(constArr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9 9]
 [9 9 9]]


### identity matrix :---

In [30]:
# Since all identity matrices are sqaure, the np.eye() function only takes a single integer as an argument
# e.g. :- 4 x 4 Identity matrix
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Diagonal Matrix :---

In [ ]:
# 5 x 5 diagonal matrix that contains the numbers 10,20,30,40 and 50 on its main diagonal
diagMatrix = np.diag([10,20,30,40,50])
print(diagMatrix)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


### Arrange :---

In [ ]:
# Rank 1 ndarray that has sequential integers from 0 to 9
seqArr_1 = np.arange(10)
print(seqArr_1)

# Rank 1 ndarray that has sequential integers from 5 to 13
# syntax :- (start, stop+1)
seqArr_2 = np.arange(5,14)
print(seqArr_2)

# Rank 1 ndarray that has sequential integers from 7 to 25 in steps/gaps of 2
# syntax :- (start, stop+1, step_size)
seqArr_3 = np.arange(7,26,2)
print(seqArr_3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13]
[ 7  9 11 13 15 17 19 21 23 25]


### Linspace :---

In [36]:
# Even though the np.arange() function allows for non-integer steps,
# such as 0.3, the output is usually inconsistent, due to the finite
# floating point precision. For this reason, in the cases where
# non-integer steps are required, it is usually better to use linspace()
# because np.linspace() uses the number of elements we want in a
# particular interval, instead of the step between values.
# linspace returns N evenly spaced numbers over the closed interval [start, stop]
# syntax :- np.linspace(start, stop, N)
# x = [ 0. 2.77777778 5.55555556 8.33333333 11.11111111 13.88888889 16.66666667 19.44444444 22.22222222 25. ]
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
