# 🚀 NumPy: The Powerhouse of Numerical Computing in Python

NumPy provides Python with an **extensive math library** capable of performing numerical computations effectively and efficiently.

---

## 🆚 Python Lists vs NumPy Arrays

While Python lists are incredibly flexible, **NumPy offers significant advantages**, especially when working with large datasets:

### ⚡ Speed
- NumPy can be **orders of magnitude faster** than native Python lists.
- This speed comes from:
  - **Memory-efficient** layout of NumPy arrays.
  - **Optimized C-based algorithms** used under the hood for arithmetic, statistics, and linear algebra.

---

## 🔢 Multidimensional Arrays: Vectors & Matrices

One of the biggest flexes of NumPy is its **support for multidimensional arrays**:

- NumPy arrays (also called `ndarray`) can represent:
  - **Vectors** (1D arrays)
  - **Matrices** (2D arrays)
  - **Tensors** (3D+ arrays)

---

## 🧠 Core Concept: The `ndarray`

At the core of NumPy lies the:

```python
ndarray  # nd stands for "n-dimensional"


In [1]:
import numpy as np

## Create ndarray :---

In [2]:
# Creating an 1D ndarray that contains only integers
a = np.array([10,20,30,40,50])
print('a =',a) # a = [10,20,30,40,50]
print('a has dimensions: ',a.shape) # a has dimention: (5,)
print('The elemnt in a are of type: ', a.dtype) # The element in a are of type: int64

# Creating a 2D ndarray that conatins only integers
b = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('b has dimentions: ', b.shape) # b has dimentions:  (4, 3)
print('b has a total of', b.size, ' elements') # b has a total of 12  elements
print('b has an object of type: ', type(b)) # b has an object of type:  <class 'numpy.ndarray'>
print('The elements of b are of type: ', b.dtype) # The elements of b are of type:  int64

a = [10 20 30 40 50]
a has dimensions:  (5,)
The elemnt in a are of type:  int64
b has dimentions:  (4, 3)
b has a total of 12  elements
b has an object of type:  <class 'numpy.ndarray'>
The elements of b are of type:  int64


## Create ndarray with dtype :---

In [3]:
# Specifying the dtype when creating the ndarray
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(x)

# If i'll give an big number but give dtype very small then obviously it will throw error, e.g. :---
# y = np.array([1,22222,3333333,444], dtype=np.int8) # throw error :- OverflowError: Python integer 22222 out of bounds for int8
# so have to give big dtype
y = np.array([1,22222,3333333,444], dtype=np.int32)
print(y)

[1 2 3 4 5]
[      1   22222 3333333     444]


## Save and load :---

In [4]:
# saving an array into a file
np.save('saved_array', x)

# Now loading the saved array from current Directory
y = np.load('./saved_array.npy')
print(y)

[1 2 3 4 5]


## Zeros, Ones, Full :---

In [5]:
# Creating ndarray using built-in functions
# 2 x 3 ndarray full of zeros
# synts :- np.zeros(shape)
zeroArr = np.zeros((2,3))
print(zeroArr)

# a 3 x 2 matrix full of ones
# syntax :- np.ones((3,2))
oneArr = np.ones((3,2))
print(oneArr)

# 2 x 3 ndarray full of 9's
# syntax :- np.full(shape, constant_value)
constArr = np.full((2,3), 9)
print(constArr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9 9]
 [9 9 9]]


## Identity Matrix

An **identity matrix** is a square matrix with:
- All **diagonal elements = 1**.
- All **off-diagonal elements = 0**.

When we multiply any matrix \( A \) with the identity matrix \( I \) (of the same size), we get \( A \) back.  
\[
A x I = A
\]  
\[
I x A = A
\]


In [6]:
# Since all identity matrices are sqaure, the np.eye() function only takes a single integer as an argument
# e.g. :- 4 x 4 Identity matrixnp.ones
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Diagonal Matrix :---
 
A **diagonal matrix** is a **square matrix** where:
- All **off-diagonal elements = 0**
- Diagonal elements can be **any value** (positive, negative, or zero)

In [7]:
# 5 x 5 diagonal matrix that contains the numbers 10,20,30,40 and 50 on its main diagonal
diagMatrix = np.diag([10,20,30,40,50])
print(diagMatrix)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


## Transpose Matrix :---

here row becomes column & colums becomes row

In [8]:
print('Before transposing : \n',ar)
print('After transposing : \n',ar.T)

NameError: name 'ar' is not defined

## Flat :---

In [ ]:
makeFlat = ar.flat

for stuffs in makeFlat :
    print(stuffs)

1
2
3
4
5
6
7
8
9


## A Range :---

In [ ]:
# Rank 1 ndarray that has sequential integers from 0 to 9
seqArr_1 = np.arange(10)
print(seqArr_1)

# Rank 1 ndarray that has sequential integers from 5 to 13
# syntax :- (start, stop+1)
seqArr_2 = np.arange(5,14)
print(seqArr_2)

# Rank 1 ndarray that has sequential integers from 7 to 25 in steps/gaps of 2
# syntax :- (start, stop+1, step_size)
seqArr_3 = np.arange(7,26,2)
print(seqArr_3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13]
[ 7  9 11 13 15 17 19 21 23 25]


# Linspace :---

### 🔍 Why `linspace()` over `arange()`?
Even though the `np.arange()` function allows for **non-integer steps** (e.g., `0.3`),  
its output can be inconsistent due to **finite floating-point precision**.

✅ In cases where non-integer steps are needed, it’s usually better to use **`np.linspace()`** because:
- It **specifies the number of elements** in the range, not the step size.
- It produces evenly spaced numbers over the interval `[start, stop]`.

---

## 🛠 Syntax
```python
np.linspace(start, stop, how_many_nums_u_wanna_print)

where ;
start → First value in the sequence
stop → Last value in the sequence (inclusive)
num → Number of evenly spaced values to generate


📐 How linspace() Calculates Step Size :

Step size = (stop - start) / (num - 1)

Example :--
Step size = (25 - 0) / (10 - 1)
          = 25 / 9
          ≈ 2.77777777...

📊 Process
0.0
0.0 + 2.777...  = 2.777...
2.777... + 2.777... = 5.555...
...
up to 25.0 (exactly)

# ⚠️mportant
# i.e. from start(0) to stop(25) , 10 numbers will be printed in gap of 2.7777777 , understood ? 😜


In [ ]:
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


## Reshape :---

In [ ]:
# syntsx :- np.reshape(ndarray, new_shape)
# it converts the given ndarray into the specified new shape 

# without re-shaping
arr = np.arange(1,21)
print('Before re-shaping :--\n',arr)

# After Re-shaping 
arr = arr.reshape(4,5)
print('\nAfter re-shaping :--\n',arr)

# reshapingArr = np.reshape(reshapingArr, (4,5))
# --------------or---------------
reshapingArr_2 = np.arange(1,33).reshape(4,8)
print(f'\nusing all methods in one line :-- \n{reshapingArr_2}')

# ⚠️⚠️⚠️ IMPORTANT  ⚠️⚠️⚠️
# The multiplication of shape values e.g. (4,8) should be equal with created array boxes, e.g. arange(1,33), 
# here in {1,33} i.e. 33-1=32 boxes r there inside array , so 4*8 = 32 so it's VALID array with shape, otherwise it will throw error, abviously, if array number mismatches

reshapingArr_3 = np.linspace(0,30,8).reshape(2,4)
print('\n',reshapingArr_3)

# One great feature about NumPy, is that some functions can also be
# applied as methods. This allows us to apply different functions in
# sequence in just one line of code

Before re-shaping :--
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After re-shaping :--
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

using all methods in one line :-- 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]

 [[ 0.          4.28571429  8.57142857 12.85714286]
 [17.14285714 21.42857143 25.71428571 30.        ]]


## Ravel :--

In [ ]:
# It will make ndarray to a straight 1D array
arr = arr.ravel()
print(arr)
arr.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


(20,)

## Slicing :---

In [ ]:
'''
Syntaxes :-

ndarray[start:end]
ndarray[start:]
ndarray[:end]
ndarray[<start>:<stop>:<step>]
ndarray[row,column] i.e. ndarray[<rstrt>:<rstp>:<rstep> , <cstrt>:<cstp>:<cstep>] or ndarray[<rstrt>:<rstp>:<rstep>][<cstrt>:<cstp>:<cstep>]
'''
# In methods one and three, the end index is included [,)
arr = np.arange(20).reshape(5,4)
print('full arr\n',arr)

# Examples :---

# I wanna get elements from 3rdd rows[i.e. index no - 2] to last with all columns
slicedEl_1 = arr[2:,]
print('\nelements from 3rd rows to last with all columns\n',slicedEl_1)

# I wanna get elements from 3rd col onwards having all rows
slicedEl_2 = arr[:,2:,]
print('\nelements from 3rd col onwards having all rows\n',slicedEl_2)

# i wanna get elements from 2nd column to last + 3rd nd 4th row only
slicedEl_3 = arr[2:4,1:,]
print('\nelements from 2nd column to last + 3rd nd 4th row only\n',slicedEl_3)

# ⚠️⚠️⚠️ V. V. Important ⚠️⚠️⚠️
# 🔁 Slicing creates a view, not a copy. 
''' 
-> It means e.g. if i'm doing slicedEl_3 = arr[2:4,1:,], it doesn't means a changed copy of 'arr' is storing under slicedArr_3, NAH !!!!
-> It just zooming in and whatever part we'r slicing, it is just creating a view of that specified part under 'slicedEl_3' 🤣
-> That means 'slicedEl_3' is nothing but another name of the original 'arr', so whatevery changes we'll make in 'slicedEl_3' in viewed part will also be refelected in original 'arr' 

here is the proof :--- 👇
'''
slicedEl_3[0,0] = 69
slicedEl_3[1,1] = 69
slicedEl_3[0,1] = 39
slicedEl_3[1,0] = 39
print('\noriginal is changing ? :---\n',arr)

full arr
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

elements from 3rd rows to last with all columns
 [[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

elements from 3rd col onwards having all rows
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]

elements from 2nd column to last + 3rd nd 4th row only
 [[ 9 10 11]
 [13 14 15]]

original is changing ? :---
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 69 39 11]
 [12 39 69 15]
 [16 17 18 19]]


## Random :---

In [ ]:
# TO GET RANDOM FLOATs
# syntsx :--  np.random.random(shape)
randomFloats = np.random.random((2,3))
print(randomFloats)

# TO GET RANDOM INTEGERS
# syntsx :-- np.random.randint(start, stop, size = shape)
randomIntegers = np.random.randint(8,22,size=(3,2))
print(randomIntegers)

# syntx :--- np.random.normal(mean, standard deviation, size=shape)
randomGussian = np.random.normal(0,0.1,size=(500,5000))
print(randomGussian)

[[0.53123086 0.35917779 0.45251896]
 [0.91126197 0.34908985 0.57759976]]
[[14 15]
 [14 21]
 [21 20]]
[[ 0.06212769  0.04348444  0.00807673 ...  0.12150182  0.11324499
  -0.1833954 ]
 [-0.02149608 -0.05424329 -0.09194221 ... -0.0040696   0.03698465
  -0.03219237]
 [ 0.11313574 -0.04052016  0.12086885 ... -0.01676974  0.05238351
  -0.12892425]
 ...
 [-0.14196276 -0.08229978  0.04816467 ...  0.06658095 -0.0246257
  -0.01665518]
 [ 0.08697161  0.01473788 -0.05423726 ...  0.09631354 -0.011399
  -0.0281801 ]
 [ 0.20080933 -0.00925852  0.00850219 ... -0.10529885 -0.00802061
   0.1286247 ]]


### MUTABILITY :---

In [ ]:
# Change ndarray

print("Before mutating :- \n")
print(arr)

print("\nAfter mutating :---\n")
arr[3] = 60
arr[1,3] = 70
print(arr)

Before mutating :- 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 69 39 11]
 [12 39 69 15]
 [16 17 18 19]]

After mutating :---

[[ 0  1  2  3]
 [ 4  5  6 70]
 [ 8 69 39 11]
 [60 60 60 60]
 [16 17 18 19]]


# Axis :--

**There are 2 axes**

- axis=0 : ROW-Axis
- axis=1 : COLUMN-Axis

In [ ]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Axis-Wise SUM
print(ar.sum(axis=0)) # axis=0 means rows, so think like each rows are collapsing over below rows to add, i.e. DOWNWARD-Row-Addition
print('\n',ar.sum(axis=1)) # axis=1 means columns, so think like each columns are collapsing over side columns to add, i.e. SIDEWISE-Column-Addition

[ 6 15 24]

 [12 15 18]


## Delete :--

In [ ]:
# Syntax :-- np.delete(ndarray, elements, axis)
A = np.array([10,20,30,60,50,40])
# Here i wanna delete 2nd & 4th element of A aray, i.e. 20 & 60
A = np.delete(A, [1,3])
print(A)

B = np.array([[12,34,56],[13,24,35],[14,25,36]])
# Now i wanna delete second row of B
B = np.delete(B, 1, axis=0) # wanna delete 2nd row, so here, '1' means 2nd + 'axis=0' means 'row'  = lo ho gaya '2nd row' 😅
print(B)

# Now i wanna delete 3rd column
B = np.delete(B, 2, axis=1) # wanna delete 3rd column, so, '2' means 3rd + 'axis=1' means 'row' = 3rd row
print(B)

[10 30 50 40]
[[12 34 56]
 [14 25 36]]
[[12 34]
 [14 25]]


## Append :---

In [ ]:
# Syntax :- np.append(ndarray, elements, axis)

arr = [11,22,33,44,55]

# I wanna add 66 here in the above array 
arr = np.append(arr, 66)
print(arr)

# I wanna add [77,88,99] in the above array 
arr = np.append(arr, [77,88,99])
print(arr)

# -------------------------------------------------------------------------------
arr2 = [[10,20,30]]
# I wanna append a new ROW
arr2 = np.append(arr2, [[40,50,60]], axis=0) # ⚠️ REMEMBER ⚠️: cuz we're appending another row in an 2D arr, so have to write [[40,50,60]] in double bracket i.e. 2D format
print(arr2)

# Now adding a new column
arr2 = np.append(arr2, [[70],[80]], axis=1)
print(arr2)

''' ⚠️ Important ⚠️
If main matrix is 2x3 i.e. 2 rows and 3 columns
-> so, if we're appending a row it should have 3 numbers i.e. to fit in 3 column
-> nd if we're appending a column, it should have 2 numbers in each separate []'es, so that it would fit in 2 rows 
'''

[11 22 33 44 55 66]
[11 22 33 44 55 66 77 88 99]
[[10 20 30]
 [40 50 60]]
[[10 20 30 70]
 [40 50 60 80]]


## Insert :---

In [ ]:
# Syntax :- np.insert(ndarray, inWhichIndexWeWannaInsert, elements, axis)
A = np.array([10,20,30,40])
B = np.array([[11,22,33],[44,55,66]])

# i wanna insert 88,99 in btn 20 & 30 in A
# i.e. 88 & 99 will start staying from 3rd position i.e. index=2
A = np.insert(A, 2, [88,99], axis=0) # here axis not necessary, cuz obviously axis would be 0 , cuz it's an !D array
print(A)

# I wanna insert a new row btn 1st & 2nd row
B = np.insert(B, 1, [77,88,99], axis=0)
print(B)

# Now i wanna insert a column btn 2nd & 3rd col
B = np.insert(B, 2, [00,00,00], axis=1)
print(B)

[10 20 88 99 30 40]
[[11 22 33]
 [77 88 99]
 [44 55 66]]
[[11 22  0 33]
 [77 88  0 99]
 [44 55  0 66]]


## Stacking :---

- NumPy also allows us to stack ndarrays on top of each other,
or to stack them side by side. 
- The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. 
- It is important to note that in order to stack ndarrays, the shape of the ndarrays must match.

In [ ]:
arr = np.array([10,30])
arr_2 = np.array([[3,2],[5,4]])

stacked_Arr_1 = np.vstack((arr,arr_2))
print(stacked_Arr_1)

stacked_Arr_2 = np.hstack((arr_2,arr.reshape(2,1)))
print(stacked_Arr_2)

[[10 30]
 [ 3  2]
 [ 5  4]]
[[ 3  2 10]
 [ 5  4 30]]


## Copy :--
- If we want to create a new ndarray that contains a copy of the values in the slice we need to use the np.copy()
- Syntax :- np.copy(array_like, order)
    - array_like: Input data (array or array-like object)
    - order: {'C', 'F', 'A', 'K'} - Memory layout of the copy (optional)
        - order='C' : C order
        - order='F' : Fortran order
        - order='A' : Same as original
        - order='K' : Keep layout


In [ ]:
original = np.array([1,2,3,4,5])
copied = np.copy(original, order='K')
print(copied)

[1 2 3 4 5]


## Extracting elements along the diagram :--

#### syntax: np.diag(array, k)
    where default is k=0, which refers to the main diagonal.
    Values of k > 0 are used to select elements in diagonals above the main diagonal
    values of k < 0 are used to select elements in diagonals below the main diagonal.

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
# Extract elements along the diagonal

# ------ Main Diagonal (k=0, default) ----------
diag_1 = np.diag(arr)
print("Main diagonal (default k=0): \n",diag_1)

# ------ Above Main Diagonal (k>0) -----------
diag_2 = np.diag(arr, k=1)
print("Above Main Diagonal :- \n",diag_2)

# ------- Below Main Diagonal (k<0) -----------
diag_3 = np.diag(arr, k=-1)
print("Below Main Diagonal:- \n",diag_3)

Main diagonal (default k=0): 
 [ 1  6 11 16]
Above Main Diagonal :- 
 [ 2  7 12]
Below Main Diagonal:- 
 [ 5 10 15]


## Finding Unique Elements :---

In [ ]:
arr = np.array([[21,34,21],[90,34,10],[34,21,11]])
unique_El = np.unique(arr)
print(unique_El)

[10 11 21 34 90]


## Boolean Indexing :---

In [ ]:
booool = np.arange(10).reshape(2,5)
print(booool)
print('Elements in boool which are greater than 5: ',booool[booool>5])
print('Elements in boool which are between 10 to 20: ',booool[(booool>10) & (booool<20)])

[[0 1 2 3 4]
 [5 6 7 8 9]]
Elements in boool which are greater than 5:  [6 7 8 9]
Elements in boool which are between 10 to 20:  []


## Set Operations :---

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,2,6,1,7,9])
print("Elements which are +nt in both arr1 & arr2: ", np.intersect1d(arr1,arr2))
print("The elements that are in arr1 that are not in arr2:", np.setdiff1d(arr1,arr2))
print("All elements of arr1 & arr2: ", np.union1d(arr1,arr2))

Elements which are +nt in both arr1 & arr2:  [1 2 5]
The elements that are in arr1 that are not in arr2: [3 4]
All elements of arr1 & arr2:  [1 2 3 4 5 6 7 9]


## Sorting :---

In [ ]:
# When used as a function, it doesn't change the original ndarray
arr1 = np.array([33,69,10,92,1])
print("before:",arr1)
sortedArr = np.sort(arr1)
print("after:",sortedArr)

# When used as a method, the original array will be sorted
arr2 = np.array([90,38,11,36,29,100])
print("\nbefore:",arr2)
arr2.sort()
print("after:",arr2)

before: [33 69 10 92  1]
after: [ 1 10 33 69 92]

before: [ 90  38  11  36  29 100]
after: [ 11  29  36  38  90 100]


## Math Operations :---

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,2,6,1,7])

add = np.add(arr1,arr2)
print(add)

subtract = np.subtract(arr1,arr2)
print(subtract)

multiply = np.multiply(arr1,arr2)
print(multiply)

divide = np.divide(arr1,arr2)
print(divide)

# In order to do these operations the shapes of the ndarray being operated on, must have the same shape or be broadcastable
arr3 = np.array([1,2,3,4]).reshape(2,2)
arr4 = np.array([1.1,1.2,1.3,1.4]).reshape(2,2)

add2 = np.add(arr3,arr4)
print(add2)

subtract2 = np.subtract(arr3,arr4)
print(subtract2)

multiply2 = np.multiply(arr3,arr4)
print(multiply2)

divide2 = np.divide(arr3,arr4)
print(divide2)

[ 6  4  9  5 12]
[-4  0 -3  3 -2]
[ 5  4 18  4 35]
[0.2        1.         0.5        4.         0.71428571]
[[2.1 3.2]
 [4.3 5.4]]
[[-0.1  0.8]
 [ 1.7  2.6]]
[[1.1 2.4]
 [3.9 5.6]]
[[0.90909091 1.66666667]
 [2.30769231 2.85714286]]


## Statistical Functions :---

In [ ]:
arr = np.array([[3,21,5],[10,8,32]])
print("Average of all elements in arr:",arr.mean())
print("Average of all elements in columns of arr:",arr.mean(axis=0))
print("Average of all elements in rows of arr:",arr.mean(axis=1))
print("Sum of all elements in arr:",arr.sum())
print('Standard Deviation of all elements in arr:', arr.std())
print('Median of all elements in arr:', np.median(arr))
print('Maximum value of all elements in arr:', arr.max())
print('Minimum value of all elements in arr:', arr.min())

Average of all elements in arr: 13.166666666666666
Average of all elements in columns of arr: [ 6.5 14.5 18.5]
Average of all elements in rows of arr: [ 9.66666667 16.66666667]
Sum of all elements in arr: 79
Standard Deviation of all elements in arr: 10.188501143718616
Median of all elements in arr: 9.0
Maximum value of all elements in arr: 32
Minimum value of all elements in arr: 3


## Broadcasting :---
Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be used in arithmetic operations. The smaller array is "broadcast" across the larger array to make their shapes compatible.

In [ ]:
# Scalar broadcasting - VERY COMMON in ML
X = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Scalar Broadcasting:")
print("4 * X = \n",4 * X) # Multiply every element by 4
print("4 + X = \n",4 + X) # Add 4 to every element
print("4 - X = \n",4 - X) # Subtract every element from 4
print("4 / X = \n",4 / X) # Divide 4 by every element 

# Array broadcasting - ESSENTIAL for ML operations
x = np.array([1, 2, 3])           # 1D array (1x3)
Y = np.array([[1, 2, 3],          # 2D array (3x3)
              [4, 5, 6],
              [7, 8, 9]])
Z = np.array([1, 2, 3]).reshape(3, 1)  # Column vector (3x1)

print("\nArray Broadcasting:")
print("x + Y =")      # Row vector + matrix
print(x + Y)

print("\nZ + Y =")    # Column vector + matrix  
print(Z + Y)

Scalar Broadcasting:
4 * X = 
 [[ 4  8 12]
 [16 20 24]]
4 + X = 
 [[ 5  6  7]
 [ 8  9 10]]
4 - X = 
 [[ 3  2  1]
 [ 0 -1 -2]]
4 / X = 
 [[4.         2.         1.33333333]
 [1.         0.8        0.66666667]]

Array Broadcasting:
x + Y =
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y =
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


## Universal Function :---

In [16]:
arr = np.array([10,20,30,40,50])

# Square-root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
