# 🚀 NumPy: The Powerhouse of Numerical Computing in Python

NumPy provides Python with an **extensive math library** capable of performing numerical computations effectively and efficiently.

---

## 🆚 Python Lists vs NumPy Arrays

While Python lists are incredibly flexible, **NumPy offers significant advantages**, especially when working with large datasets:

### ⚡ Speed
- NumPy can be **orders of magnitude faster** than native Python lists.
- This speed comes from:
  - **Memory-efficient** layout of NumPy arrays.
  - **Optimized C-based algorithms** used under the hood for arithmetic, statistics, and linear algebra.

---

## 🔢 Multidimensional Arrays: Vectors & Matrices

One of the biggest flexes of NumPy is its **support for multidimensional arrays**:

- NumPy arrays (also called `ndarray`) can represent:
  - **Vectors** (1D arrays)
  - **Matrices** (2D arrays)
  - **Tensors** (3D+ arrays)

---

## 🧠 Core Concept: The `ndarray`

At the core of NumPy lies the:

```python
ndarray  # nd stands for "n-dimensional"


In [1]:
import numpy as np

## Create ndarray :---

In [2]:
# Creating an 1D ndarray that contains only integers
a = np.array([10,20,30,40,50])
print('a =',a) # a = [10,20,30,40,50]
print('a has dimensions: ',a.shape) # a has dimention: (5,)
print('The elemnt in a are of type: ', a.dtype) # The element in a are of type: int64

# Creating a 2D ndarray that conatins only integers
b = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('b has dimentions: ', b.shape) # b has dimentions:  (4, 3)
print('b has a total of', b.size, ' elements') # b has a total of 12  elements
print('b has an object of type: ', type(b)) # b has an object of type:  <class 'numpy.ndarray'>
print('The elements of b are of type: ', b.dtype) # The elements of b are of type:  int64

a = [10 20 30 40 50]
a has dimensions:  (5,)
The elemnt in a are of type:  int64
b has dimentions:  (4, 3)
b has a total of 12  elements
b has an object of type:  <class 'numpy.ndarray'>
The elements of b are of type:  int64


## Create ndarray with dtype :---

In [3]:
# Specifying the dtype when creating the ndarray
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(x)

[1 2 3 4 5]


## Save and load :---

In [4]:
# saving an array into a file
np.save('saved_array', x)

# Now loading the saved array from current Directory
y = np.load('./saved_array.npy')
print(y)

[1 2 3 4 5]


## Zeros, Ones, Full :---

In [5]:
# Creating ndarray using built-in functions
# 2 x 3 ndarray full of zeros
# synts :- np.zeros(shape)
zeroArr = np.zeros((2,3))
print(zeroArr)

# a 3 x 2 matrix full of ones
# syntax :- np.ones((3,2))
oneArr = np.ones((3,2))
print(oneArr)

# 2 x 3 ndarray full of 9's
# syntax :- np.full(shape, constant_value)
constArr = np.full((2,3), 9)
print(constArr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9 9]
 [9 9 9]]


## identity matrix :---

In [6]:
# Since all identity matrices are sqaure, the np.eye() function only takes a single integer as an argument
# e.g. :- 4 x 4 Identity matrix
identityMatrix = np.eye(4)
print(identityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Diagonal Matrix :---

In [7]:
# 5 x 5 diagonal matrix that contains the numbers 10,20,30,40 and 50 on its main diagonal
diagMatrix = np.diag([10,20,30,40,50])
print(diagMatrix)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


## Arrange :---

In [8]:
# Rank 1 ndarray that has sequential integers from 0 to 9
seqArr_1 = np.arange(10)
print(seqArr_1)

# Rank 1 ndarray that has sequential integers from 5 to 13
# syntax :- (start, stop+1)
seqArr_2 = np.arange(5,14)
print(seqArr_2)

# Rank 1 ndarray that has sequential integers from 7 to 25 in steps/gaps of 2
# syntax :- (start, stop+1, step_size)
seqArr_3 = np.arange(7,26,2)
print(seqArr_3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13]
[ 7  9 11 13 15 17 19 21 23 25]


# Linspace :---

### 🔍 Why `linspace()` over `arange()`?
Even though the `np.arange()` function allows for **non-integer steps** (e.g., `0.3`),  
its output can be inconsistent due to **finite floating-point precision**.

✅ In cases where non-integer steps are needed, it’s usually better to use **`np.linspace()`** because:
- It **specifies the number of elements** in the range, not the step size.
- It produces evenly spaced numbers over the interval `[start, stop]`.

---

## 🛠 Syntax
```python
np.linspace(start, stop, how_many_nums_u_wanna_print)

where ;
start → First value in the sequence
stop → Last value in the sequence (inclusive)
num → Number of evenly spaced values to generate


📐 How linspace() Calculates Step Size :

Step size = (stop - start) / (num - 1)

Example :--
Step size = (25 - 0) / (10 - 1)
          = 25 / 9
          ≈ 2.77777777...

📊 Process
0.0
0.0 + 2.777...  = 2.777...
2.777... + 2.777... = 5.555...
...
up to 25.0 (exactly)

# ⚠️mportant
# i.e. from start(0) to stop(25) , 10 numbers will be printed in gap of 2.7777777 , understood ? 😜


In [9]:
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


## Reshape :---

In [10]:
# syntsx :- np.reshape(ndarray, new_shape)
# it converts the given ndarray into the specified new shape 

# without re-shaping
arr = np.arange(1,21)
print('Before re-shaping :--\n',arr)

# After Re-shaping 
arr = arr.reshape(4,5)
print('\nAfter re-shaping :--\n',arr)

# reshapingArr = np.reshape(reshapingArr, (4,5))
# --------------or---------------
reshapingArr_2 = np.arange(1,33).reshape(4,8)
print(f'\nusing all methods in one line :-- \n{reshapingArr_2}')

# ⚠️⚠️⚠️ IMPORTANT  ⚠️⚠️⚠️
# The multiplication of shape values e.g. (4,8) should be equal with created array boxes, e.g. arange(1,33), 
# here in {1,33} i.e. 33-1=32 boxes r there inside array , so 4*8 = 32 so it's VALID array with shape, otherwise it will throw error, abviously, if array number mismatches

reshapingArr_3 = np.linspace(0,30,8).reshape(2,4)
print(reshapingArr_3)

# One great feature about NumPy, is that some functions can also be
# applied as methods. This allows us to apply different functions in
# sequence in just one line of code

Before re-shaping :--
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After re-shaping :--
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

using all methods in one line :-- 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
[[ 0.          4.28571429  8.57142857 12.85714286]
 [17.14285714 21.42857143 25.71428571 30.        ]]


## Slicing :---

In [11]:
'''
Syntaxes :-

ndarray[start:end]
ndarray[start:]
ndarray[:end]
ndarray[<start>:<stop>:<step>]
'''
# In methods one and three, the end index is included [,)
arr = np.arange(20).reshape(5,4)
print('full arr\n',arr)

# Examples :---

# I wanna get elements from 3rdd rows[i.e. index no - 2] to last with all columns
slicedEl_1 = arr[2:,]
print('\nelements from 3rd rows to last with all columns\n',slicedEl_1)

# I wanna get elements from 3rd col onwards having all rows
slicedEl_2 = arr[:,2:,]
print('\nelements from 3rd col onwards having all rows\n',slicedEl_2)

# i wanna get elements from 2nd column to last + 3rd nd 4th row only
slicedEl_3 = arr[2:4,1:,]
print('\nelements from 2nd column to last + 3rd nd 4th row only\n',slicedEl_3)

# ⚠️⚠️⚠️ V. V. Important ⚠️⚠️⚠️
# 🔁 Slicing creates a view, not a copy. 
''' 
-> It means e.g. if i'm doing slicedEl_3 = arr[2:4,1:,], it doesn't means a changed copy of 'arr' is storing under slicedArr_3, NAH !!!!
-> It just zooming in and whatever part we'r slicing, it is just creating a view of that specified part under 'slicedEl_3' 🤣
-> That means 'slicedEl_3' is nothing but another name of the original 'arr', so whatevery changes we'll make in 'slicedEl_3' in viewed part will also be refelected in original 'arr' 

here is the proof :--- 👇
'''
slicedEl_3[0,0] = 69
slicedEl_3[1,1] = 69
slicedEl_3[0,1] = 39
slicedEl_3[1,0] = 39
print('\noriginal is changing ? :---\n',arr)

full arr
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

elements from 3rd rows to last with all columns
 [[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

elements from 3rd col onwards having all rows
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]

elements from 2nd column to last + 3rd nd 4th row only
 [[ 9 10 11]
 [13 14 15]]

original is changing ? :---
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8 69 39 11]
 [12 39 69 15]
 [16 17 18 19]]


## Random :---

[1 0]
